service:
  name: aws-nodejs-typescript

# Load custom configuration values to keep out of github
custom: ${file(./private.config.yml)}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: prod
  runtime: nodejs6.10
  region: us-east-1
  deploymentBucket:
    name: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}"


functions:
  CORS:
    handler: src/cors.cors
    name: ${self:custom.lambdaPrefix}-cors
    events:
      - http:
          path: /
          method: options
  logPost:
    handler: src/add.add
    name: ${self:custom.lambdaPrefix}-post
    events:
      - http: 
          path: /
          method: post
  queryPost:
    handler: src/query.query
    name: ${self:custom.lambdaPrefix}-query-post
    events:
      - http: 
          path: /query
          method: post
  queryOptions:
    handler: src/cors.cors
    name: ${self:custom.lambdaPrefix}-query-options
    events:
      - http: 
          path: /query
          method: options
  appsGet:
    handler: src/apps.apps
    name: ${self:custom.lambdaPrefix}-apps-get
    events:
      - http: 
          path: /apps
          method: get
  appsOptions:
    handler: src/cors.cors
    name: ${self:custom.lambdaPrefix}-apps-options
    events:
      - http: 
          path: /apps
          method: options
  logtypesOptions:
    handler: src/cors.cors
    name: ${self:custom.lambdaPrefix}-logtypes-options
    events:
      - http: 
          path: /logtypes
          method: options
  logtypesPost:
    handler: src/logtypes.logtypes
    name: ${self:custom.lambdaPrefix}-logtypes-post
    events:
      - http: 
          path: /logtypes
          method: post

resources:  
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.apiName} # The custom name for the API
    ThothDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}