service:
  name: aws-nodejs-typescript

# Load custom configuration values to keep out of github
custom: ${file(./private.config.yml)}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: prod
  runtime: nodejs6.10
  region: us-east-1
  deploymentBucket:
    name: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}"


functions:
  logPost:
    handler: handler.logPost
    name: ${self:custom.lambdaPrefix}-post
    events:
      - http: 
          path: /
          method: post
  logGet:
    handler: handler.logGet
    name: ${self:custom.lambdaPrefix}-get
    events:
      - http: 
          path: /
          method: get

resources:  
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.apiName} # The custom name for the API
    ThothDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}